on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    env:
      SITE_URL: ${{ env.SITE_URL }}
      PUBLIC_CONTACT_URL: ${{ env.PUBLIC_CONTACT_URL }}
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          node-version: "latest"

      - name: 🔨 Build Project
        run: |
          bun install
          bun run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --exclude-from='deploy-exclude-file.txt' --delete
          remote_path: ${{ secrets.FTP_PATH_PRODUCTION }}
          remote_host: ${{ secrets.FTP_HOST }}
          remote_user: ${{ secrets.FTP_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
